[package]
name = "ntfs_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ntfs = "0.3.1"
anyhow = "1.0.71"
argparse = "0.2.2"